### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by Aidasvenc**
Global project structure has now been defined. Let's go through it:

- `screens` folder will contain all screens in the app. It is furthermore divided into flows: `Onboarding` , `Registration`, `Profile` etc. Each such folder can contain one or multiple screens, e.g. `Registration` has multiple screens: `AuthenticationScreen`, `InterestsScreen`, `InformationScreen`. Each screen has its' own folder with two files: `___Screen.tsx` and `styles.ts`. One will contain the component itself and one will contain the style sheet for that screen. It is done for convenience, since style sheets can get extensively large. Feel free to add flows and screens based on our Figma mockup, but make sure to follow the conventions.
-  `components` folder consists of re-usable components that can be re-used in more than one screen, e.g. `InputField` (that will be re-used in the registration flow), `LargeButton` (a large wide button to proceed), `SmallButton` (you can already see many such small buttons in the Figma mockup). Each such component has its' own folder with two files - the same idea as with screens.
- `navigation` folder will contain all navigation related items: navigation containers, stacks and tab navigators. This is where @alexandre-mrt will #9  
- `assets` folder contains `images` and `colors`. We defined a global file there to store the color definitions to not have to re-define colors each time, e.g. `peach` color that represents uniconnect branding stands for `#FD9890`.

All in all, this will help us to structure the project files in a unified manner and will ultimately help us easily navigate over many files that will be created in the future. Please add your remarks and suggestions for further project structure improvement.

### CODE REVIEW

**Comment by Aidasvenc** [comment]
Additional code style and formatting rules are needed:

- no semicolons
- enforced indenting of 2 spaces

**Review by Fyuryy — APPROVED** [review]
Nice job!

**Comment by GustaveCharles** [comment]
LGTM

**Review by GustaveCharles — COMMENTED** [review]
LGTM

**Pull request merged**
